import { Geist } from "next/font/google";
import "@/app/globals.css";


const geistSans = Geist({ subsets: ["latin"] });


export const metadata = {
  title: "Mi primera app",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={geistSans.className + ' antialiased min-h-screen'}
      >
        <nav className="text-xl bg-blue-300 p-4 flex justify-between miclase">
          <a href="/">INICIO</a>
          <a href="/tienda">TIENDA</a>
          <a href="/blog">BLOG</a>
          <a href="/acerca">ACERCA DE</a>
          <a href="/registro">REGISTRO</a>
        </nav>
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  )

}
